near final SRM 0.1.0 version
Origent/ServeRmore pull request #10
Opened 2021-01-28 20:24 UTC by adconk

Hey @jonadata13 - here's the latest code for review in anticipation of ServeRmore 0.1.0.  This request is to merge my personal branch into the main pre-release branch, which also was forked from your branch a number of days back.  Would you be willing to destroy/remove your other individual branches?

You can find updated instructions in both the main README and the layers/README, and the story is here:
https://app.clubhouse.io/origent/story/15282/peer-review-test-suite-validation

Please let me know if you have any questions with this build and deployment process versus the previous one from a few weeks ago.

2021-02-01 16:10 UTC, adconk commented
Hi @jonadata13 - I've merged your PR into this one.  Also, I've made another attempt as simplifying the instructions by merging both READMEs.  Let me know what you think!

2021-02-01 18:51 UTC, jonadata13 requested changes
@adconk - The updates are looking awesome! Thank you for adding more information regarding the YAML file parameters. I just have two minor requests (see below).

2021-02-01 18:51 UTC, jonadata13 commented on README.md
> +* `instance_type`: The type detrmines cost and capability of the virtual machine.  The type provided has been tested, but many others could potentially work.
Spelling error: _determines_

2021-02-01 18:51 UTC, jonadata13 commented on README.md
> +`FILENAME`: ServeRmore/layer/r-runtime/build/layers/r-runtime/build/layer/R/library/base/R/Rprofile
Can you add a bullet point for `FILENAME` and `METHOD`?

2021-02-01 21:02 UTC, adconk commented
Hey @jonadata13 - all set.  I rewrote the section on debugging.  What else ya got?

2021-02-01 22:14 UTC, jonadata13 requested changes
_Two_ more minor requests!

2021-02-01 22:14 UTC, jonadata13 commented on README.md
> +There's also a way to introduce print log statements int the Lambda R Runtime layer that will add log entries into AWS CloudWatch from AWS Lambda.  Once inside the Docker container, change directorie
Spelling error: _in_

2021-02-01 22:14 UTC, jonadata13 commented on README.md
> +If there are challenges with the layer build, there are ways to enter into an interactive mode. First, make sure that you've already run deploy once before without terminating. Next, check the status
Comma after 'Finally'

2021-02-02 03:24 UTC, adconk commented
Done! @jonadata13 - got anything else for me?

2021-02-02 14:25 UTC, jonadata13 commented
@adconk Everything looks good! 🎉

2021-02-02 14:25 UTC, merged